// src/modules/analytics/dto/top-restaurant.dto.ts

import { ApiProperty } from '@nestjs/swagger';

export class TopRestaurantDto {
  @ApiProperty({ description: 'The UUID of the restaurant.' })
  restaurantId: string;

  @ApiProperty({
    description: 'The name of the restaurant.',
    example: 'The Gourmet Kitchen',
  })
  restaurantName: string;

  @ApiProperty({
    description: 'Total revenue generated by this restaurant from completed orders in the last 30 days.',
    example: 15200.5,
  })
  totalRevenue: number;
}